Project_1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

auctions/urls.py
from django.urls import path

from . import views


app_name = 'auction'
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create_listing", views.create_listing, name ="create_listing"),
    path("listing/<int:id>", views.listing, name ="listing"),
    path("<str:user>/watchlist", views.watchlist, name ="watchlist"),
    path("categories", views.categories, name ="categories"),
    path("categories/<str:title>", views.category, name = 'category'),
    path("<int:id>/bid", views.bid, name = 'bid'),
    path("/<int:id>/new_comment", views.new_comment, name ='new_comment')
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.db.models.enums import Choices

class User(AbstractUser):
    pass

class Categories (models.Model): 
    category = models.CharField(max_length=64)

    def __str__ (self): 
        return f'{self.category}'

class Listing (models.Model): 
    product_name = models.CharField(max_length=64)
    description = models.CharField(max_length=300, default='Default description') 
    price = models.IntegerField()
    img = models.URLField(blank = True, null = True)
    owner = models.ForeignKey(User, on_delete= models.CASCADE, related_name = 'items')
    category = models.ForeignKey(Categories, on_delete=CASCADE, blank = True, null=True)
    t_create = models.DateTimeField(auto_now_add=True)

    h_bidder = models.ForeignKey(User, blank=True, on_delete=CASCADE, related_name="highest_bidder", null=True)
    h_bid = models.IntegerField(blank=True, null=True, default=0)
    active = models.BooleanField(default='True')

    def __str__ (self): 
        return f'{self.product_name}'

class Bid (models.Model): 
    bid = models.PositiveIntegerField() 
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name = "bids_on_products")
    item = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='item_bids')

    def __str__ (self): 
        return f'{self.item}: {self.bid}'

class Comment (models.Model):
    title = models.CharField(max_length=64) 
    text = models.CharField(max_length=64)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comments')
    item = models.ForeignKey(Listing,on_delete=models.CASCADE, related_name='item_comments')

    def __str__ (self): 
        return f'{self.title}: ({self.user})'

class Watchlist (models.Model): 
    item = models.ForeignKey(Listing, on_delete=CASCADE, related_name='on_watchlist')
    user = models.ForeignKey(User, on_delete=CASCADE, related_name='watchlist')
    watched = models.BooleanField(default=False)

    def __str__ (self): 
        return f'{self.user}: ({self.item})'
        

auctions/forms.py
from django.db import models
from django.db.models import fields
from django.forms import ModelForm, Textarea, widgets
from django import forms 
from auctions.models import Listing, Bid, Comment
from django.utils.translation import gettext_lazy as _


#Creating new listing 
class NewListing (ModelForm): 
    class Meta: 
        model = Listing
        fields = '__all__'
        exclude = ['owner','h_bidder', 'h_bid', 'active']
        widgets = { 
            'description': Textarea(attrs={'col': 80, 'rows': 20}),
        }
        labels = {
            'product_name': _("Product title")
        }

#Add new comment 
class NewComment (ModelForm):
    class Meta: 
        model= Comment
        fields= '__all__'
        exclude = ['item', 'user'] 
        widgets = {
            'text': Textarea(attrs={'col': 80, 'rows': 20})
        }

#New item bid 
class NewBid (ModelForm): 
    class Meta: 
        model = Bid 
        fields = ['bid']
        labels = {
            'bid': _('Place your bid')
        }
        

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError, connections
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.translation import activate, templatize
from .forms import NewListing, NewBid, NewComment
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Categories, User, Bid, Comment, Watchlist, Listing  

def index(request):
    #find all listings in database 
    #pass it to the template
    items = Listing.objects.all()

    return render(request, "auctions/index.html", {
        "items":items
    })

#function to create a new listing 
@login_required
def create_listing (request): 
    if request.method == "POST":
        form = NewListing(request.POST)

        if form.is_valid(): 
            new_item = form.save(commit=False)
            new_item.owner = request.user 
            new_item.save()

            return HttpResponseRedirect(reverse("auction:listing", args=(new_item.pk,)))

    else: 
        form = NewListing()

        return render (request, 'auctions/create_listing.html', {
            'form': form
        })
    
    return HttpResponseRedirect(reverse("auction:index"))
    

def listing (request, id): 
    #find a listing in a database 
    item = Listing.objects.get(pk = id)    
    #create a form for new bids
    f_bid = NewBid()    
    #check if owner is same user as sign in
    owner = False
    #check if highest bidder is same user as sign in
    h_bidder = False 
    #list all comments for listing 
    comments = Comment.objects.filter(item=id)

    #render newcomment form 
    f_new_comment = NewComment()

    if request.user.is_authenticated:
        name = User.objects.get (username = request.user.username)

        #look for a item owner 
        if item.owner == name:
            owner = True

        #check if log in user is highest bidder on the item 
        if item.h_bidder == name: 
            h_bidder = True    

    if request.method == 'POST':
        
        if 'close_listing' in request.POST and owner: 
            item.active = False
            item.save()

        data ={             
            'item': item,
            'owner': owner,
            'watchlist': None,
            'f_bid': f_bid,
            'h_bidder': h_bidder,
            'f_new_comment': f_new_comment,
            'comments': comments
        }
        
        return render (request, "auctions/listing.html", data)


    #try to find a item in watchlist 
    try: 
        watchlist = Watchlist.objects.get(user = name, item = item)
        data = {
            'item': item,
            'owner': owner,
            'watchlist': watchlist,
            'f_bid': f_bid,
            'h_bidder': h_bidder,
            'f_new_comment': f_new_comment, 
            'comments': comments
        }
    except: 
        data = {
            'item': item,
            'owner': owner,
            'watchlist': None,
            'f_bid': f_bid,
            'h_bidder': h_bidder,
            'f_new_comment': f_new_comment, 
            'comments': comments
        }
    return render (request, "auctions/listing.html", data)

@login_required
def watchlist (request, user): 
    if request.user.is_authenticated: 
        name = User.objects.get(pk = request.user.id)

    if request.method == "POST": 

        if 'd_watchlist' in request.POST: 
            item_id = request.POST['d_watchlist']
            watchlist = Watchlist.objects.filter(item = item_id, user = name) 
            watchlist.delete()
            return HttpResponseRedirect(reverse("auction:watchlist", args=(user,)))    


        else: 
            item_id = request.POST['item']
            item = Listing.objects.get(pk = item_id)
            watched = True
            new_watchlist = Watchlist(user = name, item= item, watched = watched)
            new_watchlist.save()
            return HttpResponseRedirect(reverse("auction:listing", args=(item_id,)))    

    else:
        #load watchlist from database 
        watchlist = Watchlist.objects.filter(user = name)
        return render (request, "auctions/watchlist.html", {
            'watchlist': watchlist
        })

@login_required
def bid (request, id): 
    if request.method == "POST":
        form = NewBid(request.POST)

        print(form.errors)

        if form.is_valid():   
            name = User.objects.get(pk = request.user.id)
            item = Listing.objects.get(pk = id)
            new_bid = form.save(commit=False)
            new_bid.bidder = name
            new_bid.item = item
            new_bid.save()


            print (new_bid.bid)
            print (item.h_bid)

            if new_bid.bid < item.h_bid or (new_bid.bid < item.price and item.h_bid == 0): 
                messages.error(request, "Sorry your bid is too low. Bid higher")
                return HttpResponseRedirect(reverse('auction:listing', args=(id,)))

            else:
                #change a bidder on listing 
                item.h_bid = new_bid.bid 
                item.h_bidder = new_bid.bidder
                item.save()

            return HttpResponseRedirect(reverse('auction:listing', args=(id,)))

        else: 
            #render error
            messages.error(request, "Sorry something is wrong, try again later.")
            return HttpResponseRedirect(reverse('auction:listing', args=(id,)))

@login_required
def new_comment (request, id): 
    if request.method == 'POST': 
        print('in post')
        form = NewComment(request.POST)
        name = User.objects.get(pk = request.user.id)
        item = Listing.objects.get(pk = id)

        if form.is_valid(): 
            new_comment = form.save (commit=False)
            new_comment.user = name
            new_comment.item = item
            new_comment.save()

            return HttpResponseRedirect(reverse('auction:listing', args=(id,)))
    else: 
        print('here')
        messages.error(request, 'Sorry something went wrong. Try again later.')
        return HttpResponseRedirect(reverse('auction:listing', args=(id,)))

def categories (request): 
    #load all categies from the datagase 
    #have acces to items in each category (might need to change models)
    categories = Categories.objects.all()

    data = {
        'categories': categories
    }    

    return render (request, "auctions/categories.html", data)

def category (request, title): 
    category = Categories.objects.get(category = title)
    items = Listing.objects.filter(category = category.id, active = True)

    data = {
        'title': title,
        'items': items
    }

    return render (request, 'auctions/category.html', data)


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auction:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auction:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auction:index"))
    else:
        return render(request, "auctions/register.html")

auctions/templates/auctions/categories.html
{% extends 'auctions/layout.html' %}
{% block body %}
    <h4>Categories</h4> 
    <ul> 
    {% for category in categories %}
        <li>
            <a href="{% url 'auction:category' category %}">{{ category }}</a>
        </li>
    {% endfor %}
    </ul> 
{% endblock %}

auctions/templates/auctions/category.html
{% extends 'auctions/layout.html' %}

{% block body %}
    <h4>{{ title }}</h4> 

    {% for item in items %}
       <a href = "{% url 'auction:listing' item.id %}">{{ item.product_name }}</a> 
       <br>
    {% endfor %}

{% endblock%}

auctions/templates/auctions/create_listing.html
{% extends 'auctions/layout.html' %}

{% block body %}
    {% if user.is_authenticated %}
        <h3>Create listing</h3> 
        <form action={% url 'auction:create_listing' %} method = "POST">
            {% csrf_token %}
            {{ form }}
            <input type='submit' value='Create New Listing'>
        </form>
        
    {% else %}
        <h3>User not signed it</h3> 
        <p>Please <a href="{% url 'auction:login' %}">sign in</a> or <a href="{% url 'auction:register' %}">register</a> to create new listing</p
    {% endif%}


{% endblock%}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class = 'mdl-grid'> 
    {% for item in items %}
    <div class = 'mdl-cell mdl-cell--4-col mdl-cell--4-col-tablet mdl-cell--4-col-phone'>
        <div class = 'product-tile'>
            <h3><a href = {% url 'auction:listing' item.id %}>{{ item.product_name}}</a></h3>
            <div> 
                {% if item.img %}
                    <img src="{{ item.img }}">
                {% endif %}
            </div>   
            <p>   
                {{ item.description }} 
            </p>
            <h5>{{ item.price }}</h5>
            <br>
            <a href = {% url 'auction:listing' item.id %}><button>Show more</button</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
        <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'auctions/style.css' %}">       
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body> 

<!-- Always shows a header, even in smaller screens. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="mdl-layout__header">
      <div class="mdl-layout__header-row">
        <!-- Title -->
        <span class="mdl-layout-title">Apple auctions</span>
        <!-- Add spacer, to align navigation to the right -->
        <div class="mdl-layout-spacer"></div>
        <!-- Navigation. We hide it in small screens. -->
        <nav class="mdl-navigation mdl-layout--large-screen-only">
                <a class="mdl-navigation__link" href="{% url 'auction:index' %}">Show All</a>
            {% if user.is_authenticated %}
                <a class="mdl-navigation__link" href="{% url 'auction:create_listing' %}">Create listing</a>
                <a class="mdl-navigation__link" href="{% url 'auction:watchlist' user.username %}">Watchlist</a>
                Signed in as <b>{{ user.username }}</b>
                <a class="mdl-navigation__link" href="{% url 'auction:logout' %}">Log Out</a>
            {% else %}
                <a class="mdl-navigation__link" href="{% url 'auction:login' %}">Log In</a>
                <a class="mdl-navigation__link" href="{% url 'auction:register' %}">Register</a>
            {% endif %}
        </nav>
      </div>
    </header>
    <div class="mdl-layout__drawer">
      <span class="mdl-layout-title">Categories</span>
      <nav class="mdl-navigation">
          {% for category in categories %}
            <a class="mdl-navigation__link" href="{% url 'auction:category' category %}">{{ category }}</a>
          {% endfor %}
      </nav>
    </div>
    <main class="mdl-layout__content">
        <div class="page-content">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

{% block body %}
{% endblock %}
        </div>
    </main>
</div>

</body>
</html>

auctions/templates/auctions/listing.html
{% extends 'auctions/layout.html' %}


{% block body %}
<h1>Listing</h1>

<ul>
    <li>  
        <h2>{{ item.product_name}} </h2>
    </li> 
    <li> 
        <p>{{ item.decription }}</p>
    </li>
    {% if item.img %}
        <li> 
            <img src='{{ item.img }}'>
        </li> 
    {% else %}
            <li>I am sorry there is not image</li> 
    {% endif %}
    <li> 
        {{ item.price }} - {{ item.h_bid }}
    </li> 
    <li>
        {% if item.active %}
            {{ item.h_bidder }}
        {% else %} 
            <h4>Winner is: {{ item.h_bidder}} with price {{ item.h_bid }}</h4>
        {% endif %}
    </li>
    <li> 
        {{ item.owner }}
    </li>
    {% if item.category %}
        <li> 
            {{ item.category }}
        </li>  
    {% else %}
        <li>
            No category
        </li> 
    {% endif %}
<ul>

{% if user.is_authenticated %}
    <p>Place for new comment</p> 

    {% if item.active %}

        {% if owner %}
            Do you want to close the bidding?
            <form action="{% url 'auction:listing' item.id %}" method="POST">
                {% csrf_token %}
                <button type ='submit' name ='close_listing'>Close Listing</button> 
            </form>
            
        {% else %}
            {% comment %} put bit on item  {% endcomment %}
            {% if h_bidder %}
                <h2>Currently you have the highest bit on the item</h2> 
            {% else %}
                <p>Form to bid on item</p>
                <form action="{% url 'auction:bid' item.id %}" method="POST">
                    {% csrf_token %}
                    {{ f_bid }}
                    <button type='submit'>Place a bid</button> 
                </form> 
            {% endif %}        

            {% comment %} Add item to watch list if on the watch list it removes it {% endcomment %}
            <form action={% url 'auction:watchlist' user.get_username %} method="POST"> 
                {% csrf_token %}
                {% if watchlist.watched %}
                    <button type= 'submit' disabled>Already on watchlist</button>
                {% else %}
                    <input type = 'hidden' value = {{ item.id }} name='item'>
                    <button type='submit' name='watchlist'>Add to watchlist</button>
                {% endif %}
            </form> 
            

        {% endif %}
    {% else %}
        {% if h_bidder %}
            <h3>You have won the auction</h3>
        {% else %}
            <h3>Listing is no longer active</h3>
        {% endif %}


    {% endif %}
{% endif %}  
<h4>Comments</h4>
    {% for comment in comments %}
    <div style='border: 1px solid black'>
        <p><b>{{ comment.title }}</b></p> 
        <p>{{ comment.text }}</p> 
        <span>{{ comment.user }} </p>
    </div>
    {% endfor%}
    {% if user.is_authenticated %}
        <form action="{% url 'auction:new_comment' item.id %}" method="POST"> 
            {% csrf_token %}
            {{ f_new_comment}}
            <button type = 'submit' name = 'new_comment'>Add new comment</button>
        </form>
    {% endif %}
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auction:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auction:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auction:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auction:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends 'auctions/layout.html' %}
{% block body %}
    This is a future watchlist for {{ user.get_username }}

    <ul> 

    {% for item in watchlist %}
        <li> 
            <a href="{% url 'auction:listing' item.item.id %}">{{ item.item }}</a><br> 
            <form action="{% url 'auction:watchlist' user.get_username %}" method="POST">
                {% csrf_token %}
                <button type='submit' name='d_watchlist' value={{item.item.id}}>Remove item form watchlist</button> 
            </form> 
        </li> 
    {% endfor %}

    </ul>
{% endblock %}